name: CI/CD Pipeline

# Executa a cada Push e Pull request na main
on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do c贸digo
      - name: Fazer checkout do c贸digo
        uses: actions/checkout@v4

      # Configura Java 21
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Executa o teste
      - name: Executar teste
        run: mvn -B verify --file pom.xml

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do c贸digo
      - name: Fazer checkout do c贸digo
        uses: actions/checkout@v4

      # Configura Java 21
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Gera o JAR para deploy
      - name: Gerar JAR para deploy
        run: mvn -B package --file pom.xml -DskipTests

      - name: Upload JAR para deploy
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
        